In [1]:
%pylab inline
import pandas as pd
import numpy as np

import torch
from torchvision import transforms
import matplotlib.pyplot as plt

import torch.nn as nn
import torch.nn.functional as F
from torch.nn.parameter import Parameter

import torch.optim as optim                          # optimization

import os
from tqdm import tqdm                                # for progress bar
from sklearn.model_selection import train_test_split
from sklearn.cluster import AgglomerativeClustering, KMeans
from sklearn.metrics import adjusted_rand_score

from clustering import clus

from numba import njit

if torch.cuda.is_available():
    device = torch.device("cuda:0")
    print("running on the gpu")
else:
    device = torch.device("cpu")
    print("running on the cpu")
    
from scDHA import scDHA

Populating the interactive namespace from numpy and matplotlib
running on the gpu


In [1]:
path = "goolam"
do_clus = True
latent = scDHA(path, False, vae_choice='paper', retrain=True, seed=1) # a list with 3 differently trained latent variables
print(len(latent), latent[0].shape)


NameError: name 'scDHA' is not defined

In [11]:
x = np.load('latent/xin.npy')
print(len(x))

1600


In [12]:
x = [np.array([1,2,3]), np.array([1,2,3]), np.array([1,2,3])]
x = np.array(x)
print(x)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


## classification

In [3]:
from Analysis import scDHA_class
res = scDHA_class('baron-human', seed=1, retrain=False)

log2 is applied
training non-negative kernel autoencoder
epoch 10 Loss:  0.0033938742708414793
epoch 10 Loss:  0.003262168727815151
epoch 10 Loss:  0.0035166756715625525
tensor([0.0855, 0.0570, 0.1690,  ..., 0.0709, 0.0375, 0.1040])
training stacked bayesian autoencoder

##############################
#phase 1: the warm-up process#
##############################
epoch 10 Loss: 0.04290628805756569

########################
#phase 2: the VAE stage#
########################
epoch 10 Loss: 2.333294630050659
epoch 20 Loss: 2.3192358016967773
training stacked bayesian autoencoder

##############################
#phase 1: the warm-up process#
##############################
epoch 10 Loss: 0.041616957634687424

########################
#phase 2: the VAE stage#
########################
epoch 10 Loss: 2.3494277000427246
epoch 20 Loss: 2.3272147178649902
training stacked bayesian autoencoder

##############################
#phase 1: the warm-up process#
##############################
epoch 10 Loss

In [3]:

if do_clus:
    # Use an ensemble of data projection models to achieve higher accuracy and to avoid local minima, not needed if we use kmeans++
    # first repeat the data projection
    labels = []
    for hidden in latent:
        # labels.append(clus(hidden, k=6, nmax=100))
        labels.append(clus(hidden, nmax=50))
    labels = np.array(labels) 
    print(labels)   
    S = np.zeros((len(labels), len(labels)))  # chance that cell i and j are in the same cluster
    for i, row in enumerate(S):
        for j, _ in enumerate(S):
            if not (i==j):
                S[i, j] = adjusted_rand_score(labels[i], labels[j])
    for i, row in enumerate(S):
        S[i,i] = row.mean()
    print(S)
    found = False
    if (S[S < 0.7]).sum() > 0:
        i = 2
    else:
        i = 1
        
    # find best guessed label (latent variable)
    while not found:
        # print(f'i={i}')
        tmp = KMeans(n_clusters = i, n_init = 100, max_iter = 5000).fit(S)
        k = tmp.labels_
        max = 0
        for c in range(tmp.cluster_centers_.shape[0]): # for k clusters
            score = S[k == c, k == c].mean()
            if score > max and (k==c).sum() > 1:
                max = score
                idx = (k == c)
        if max > 0.8:
            found = True
        if i >= 3:
            found = True
        
        i += 1
    # guess number of clusters
    tmp = []
    for label in labels[idx]:
        tmp.append(np.unique(label).shape[0])
        print(tmp)
    cluster_max = np.floor(np.mean(tmp)+0.5).astype(np.int)
    
    
    # (i) calculate cell-cell weighted similarity matrix 
    W = S * (1 - S)
    print(W.max(), W.min())
    # then combine the clustering results using the wMetaC
    # wMetaC = AgglomerativeClustering(n_clusters=k_classes, linkage='ward')
    # # wMetaC = AgglomerativeClustering(n_clusters=k_classes, affinity='precomputed')
    # wMetaC.fit(latent)
    # # wMetaC.fit(clustered.affinity_matrix_.toarray())
    # print(wMetaC)
    # print(clustered.labels_)
    # print(wMetaC.labels_)

        # print(latent.size())
    
    


(1600, 15)
finding best k...
best k is 5
running SC on k=5...
SpectralClustering(affinity='nearest_neighbors', eigen_solver='arpack',
                   n_clusters=5, n_jobs=-1, n_neighbors=7, random_state=0)
(1600, 15)
finding best k...
best k is 5
running SC on k=5...
SpectralClustering(affinity='nearest_neighbors', eigen_solver='arpack',
                   n_clusters=5, n_jobs=-1, n_neighbors=7, random_state=0)
(1600, 15)
finding best k...
best k is 5
running SC on k=5...
SpectralClustering(affinity='nearest_neighbors', eigen_solver='arpack',
                   n_clusters=5, n_jobs=-1, n_neighbors=7, random_state=0)
[[1 3 3 ... 3 1 3]
 [0 0 0 ... 0 3 1]
 [2 0 2 ... 3 3 4]]
[[ 4.09367810e-05  1.27577776e-03 -1.15296742e-03]
 [ 1.27577776e-03  6.17736990e-04  5.77433208e-04]
 [-1.15296742e-03  5.77433208e-04 -1.91844737e-04]]


NameError: name 'idx' is not defined

In [4]:
pipeline('campbell', 1000, 3, False, 1000, 5, vae_choice='paper')

training non-negative kernel autoencoder


100%|██████████| 22/22 [00:00<00:00, 106.05it/s]


Loss:  0.001624945318326354


100%|██████████| 22/22 [00:00<00:00, 107.14it/s]


Loss:  0.0016046841628849506


100%|██████████| 22/22 [00:00<00:00, 108.25it/s]


Loss:  0.0015911390073597431
training stacked bayesian autoencoder
phase 1: the warm-up process


100%|██████████| 22/22 [00:00<00:00, 154.05it/s]


Loss:  0.02688029780983925


100%|██████████| 22/22 [00:00<00:00, 159.85it/s]


Loss:  0.01863638311624527


100%|██████████| 22/22 [00:00<00:00, 152.01it/s]


Loss:  0.0181533545255661


100%|██████████| 22/22 [00:00<00:00, 156.57it/s]


Loss:  0.01757773384451866


100%|██████████| 22/22 [00:00<00:00, 161.01it/s]


Loss:  0.01729338802397251
phase 2: the VAE stage


100%|██████████| 22/22 [00:00<00:00, 132.88it/s]


Loss:  2.0298502445220947


100%|██████████| 22/22 [00:00<00:00, 140.50it/s]


Loss:  1.9593911170959473


100%|██████████| 22/22 [00:00<00:00, 116.08it/s]


Loss:  1.9687726497650146


100%|██████████| 22/22 [00:00<00:00, 139.61it/s]


Loss:  1.9809030294418335


100%|██████████| 22/22 [00:00<00:00, 146.08it/s]


Loss:  1.951000690460205


tensor([[-0.0781,  0.0789,  0.0101,  ...,  0.0791, -0.1060,  0.0511],
        [-0.0928,  0.0692,  0.0293,  ...,  0.0207, -0.0778,  0.0243],
        [-0.0822,  0.0621, -0.0014,  ...,  0.0103, -0.1345,  0.0899],
        ...,
        [-0.0850,  0.0382, -0.0398,  ...,  0.0492, -0.0836,  0.1068],
        [-0.0944,  0.0489, -0.0496,  ...,  0.0135, -0.0710,  0.1006],
        [ 0.0677,  0.8861,  0.1220,  ...,  0.1088, -0.0515, -0.2227]],
       device='cuda:0')